class Tables < ActiveRecord::Migration[6.0]
  def change
    execute <<~SQL
      create schema s1;
      create schema s2;
      create table s1.ts (t_id integer generated by default as identity primary key, a text not null);
      create table s2.ts (t_id integer generated by default as identity primary key references s1.ts, a text not null);
    SQL
  end
end
